### ISSUE TITLE
ipython is not available in brew

### ISSUE THREAD

**Issue by sammcj** [dpinney/iPythonNotebookServer#3]
```
% brew update
Updated Homebrew from 066bdb0d to 6ecb586c.
==> Updated Formulae

% brew search ipython
No formula found for "ipython".
==> Searching pull requests...
```

**Comment by dpinney** [comment]
Oops! Does `pip install ipython` work for you?

**Comment by sammcj** [comment]
No it doesn't either.
At this point I need to mention that I am running 10.11 which is still in beta but about to be released shortly.

```
% sudo pip install ipython
Password:
The directory '/Users/samm/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/samm/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ipython
  Downloading ipython-4.0.0-py2-none-any.whl (730kB)
    100% |████████████████████████████████| 733kB 459kB/s
Collecting traitlets (from ipython)
  Downloading traitlets-4.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 57kB 267kB/s
Collecting pickleshare (from ipython)
Collecting simplegeneric>0.8 (from ipython)
Collecting decorator (from ipython)
  Downloading decorator-4.0.2-py2.py3-none-any.whl
Collecting gnureadline (from ipython)
  Downloading gnureadline-6.3.3-cp27-none-macosx_10_6_intel.whl (262kB)
    100% |████████████████████████████████| 262kB 995kB/s
Collecting appnope (from ipython)
  Downloading appnope-0.1.0-py2.py3-none-any.whl
Collecting pexpect (from ipython)
Collecting ipython-genutils (from traitlets->ipython)
  Downloading ipython_genutils-0.1.0-py2.py3-none-any.whl
Collecting path.py (from pickleshare->ipython)
  Downloading path.py-7.6-py2.py3-none-any.whl
Installing collected packages: decorator, ipython-genutils, traitlets, path.py, pickleshare, simplegeneric, gnureadline, appnope, pexpect, ipython
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 299, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 813, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1008, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 371, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 310, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 70, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/share'
```

**Comment by dpinney** [comment]
Sigh. Package management.

Does this work?

`sudo pip install ipython==3.1.0`

I noticed my version is 3.1.0 and I'm pretty sure it was all installed via pip. I'm using the default Mac OS X Python (2.7) as well.

**Comment by sammcj** [comment]
hmm exactly the same, it's like ipython is trying to install files to somewhere it shouldn't be able to write to?

```
% sudo pip install ipython==3.1.0
Password:
The directory '/Users/samm/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/samm/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ipython==3.1.0
  Downloading ipython-3.1.0-py2-none-any.whl (3.4MB)
    100% |████████████████████████████████| 3.4MB 91kB/s
Requirement already satisfied (use --upgrade to upgrade): gnureadline in /Library/Python/2.7/site-packages (from ipython==3.1.0)
Installing collected packages: ipython
  Found existing installation: ipython 4.0.0
    Uninstalling ipython-4.0.0:
      Successfully uninstalled ipython-4.0.0
  Rolling back uninstall of ipython
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 299, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 813, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1008, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 371, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 310, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 70, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/share'
```

**Comment by dpinney** [comment]
Hmm. Maybe this could be part of the new security measures in 10.11? I sure wish there were light Mac OS X VMs that could be used for testing.

**Comment by sammcj** [comment]
Perhaps ipython could be installed to a local virtualenv or something rather than into the root of the OS? I'm not very familiar with how this works however.

**Comment by dpinney** [comment]
Maybe... `brew install python3` and then `pip3 install "ipython[notebook]"`? Should force everything to happen in brew's copy and not OS X's? As long as the iPythonNotebook.app can see /usr/local/bin/ipython it should work.

**Comment by abkfenris** [comment]
`brew install python` than regular `pip install python[notebook]`, works fine for me on a relatively fresh 10.11 install.

**Comment by sammcj** [comment]
OK so the issue was with the sticky bit setting on /private/tmp, this can be resolved by running:

`sudo chmod +t /private/tmp/`

and

`chown -R $USER $HOME/Library/Caches/pip`

**Comment by sammcj** [comment]
So maybe final thing would just to be to update the readme to reflect this.

**Comment by dpinney** [comment]
Thanks gents. I greatly appreciate your help debugging the iPython install. I added the brew instructions since I think those have the highest chance of working across lots of OS X versions.
